# Generated by Django 2.2.14 on 2020-07-15 07:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PenjadwalanBAAK',
            fields=[
                ('tahun_id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=15)),
                ('tanggal_dibuat', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PenjadwalanProdi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_matkul', models.CharField(max_length=10)),
                ('matkul', models.CharField(max_length=255)),
                ('kode_prodi', models.CharField(max_length=5)),
                ('total_jam', models.CharField(max_length=5)),
                ('kelas', models.CharField(max_length=5)),
                ('kode_dosen', models.CharField(max_length=10)),
                ('nama_dosen', models.CharField(max_length=255)),
                ('tipe_hari', models.CharField(blank=True, max_length=255, null=True)),
                ('tipe_ruangan', models.CharField(max_length=5)),
                ('tanggal_dibuat', models.DateTimeField(default=django.utils.timezone.now)),
                ('tahun_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polpos.PenjadwalanBAAK')),
            ],
        ),
    ]
