# Generated by Django 2.2.14 on 2020-07-07 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PenjadwalanProdi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matkul', models.CharField(max_length=255)),
                ('kode_prodi', models.CharField(max_length=5)),
                ('total_jam', models.CharField(max_length=5)),
                ('kelas', models.CharField(max_length=5)),
                ('nama_dosen', models.CharField(max_length=255)),
                ('tipe_hari', models.CharField(blank=True, max_length=255, null=True)),
                ('tipe_ruangan', models.CharField(max_length=5)),
            ],
        ),
    ]
