# Generated by Django 2.2.14 on 2020-07-14 13:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polpos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PenjadwalanBAAK',
            fields=[
                ('tahun_id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=15)),
                ('tanggal_dibuat', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='penjadwalanprodi',
            name='tanggal_dibuat',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
