# Generated by Django 2.2.14 on 2020-07-14 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polpos', '0002_auto_20200714_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='penjadwalanprodi',
            name='tahun_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polpos.PenjadwalanBAAK'),
        ),
    ]
